### ISSUE TITLE
Fix double spend on eth based networks

### ISSUE THREAD

**Issue by mNizhurin** [horizontalsystems/ethereum-kit-ios#191]
Track and increase nonce for outgoing transactions.

 Nonce provider can give same nonce when it's already used in other transaction. This leads to double spend or transaction drop-replace [https://info.etherscan.com/transaction-dropped-replaced/](docs).

**Comment by esengulov** [comment]
Duplicate of # https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/2097
