### ISSUE TITLE
Coin Type 1 for ropsten

### ISSUE THREAD

**Issue by VitaliyYarkun** [horizontalsystems/ethereum-kit-ios#199]
Hi, can you please tell, why coinType is set to 1 in Kit.swift in `public static func instance(words: [String], syncMode wordsSyncMode: WordsSyncMode, networkType: NetworkType = .mainNet, rpcApi: RpcApi, etherscanApiKey: String, walletId: String, minLogLevel: Logger.Level = .error) throws -> Kit` method for any other network except mainnet and is not the same for all and equal 60 for ETH?

**Comment by esen** [comment]
@VitaliyYarkun 

[Here](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) is a list of commonly accepted coin types values. 60 for ETH and 1 for testnet (all coins)
