### ISSUE TITLE
Token info from ContractAddress

### ISSUE THREAD

**Issue by VitaliyYarkun** [horizontalsystems/ethereum-kit-ios#212]
Hi, is there a possibility to get token info(name, coin, precision) from ContractAddress, using your toolkit?
In your example project, erc20 tokens information is hardcoded.

**Comment by ealymbaev** [comment]
Hi, no, there is no such possibility in EthereumKit. But we have implemented alternative solution for our `Add Erc20 Token` feature in `Unstoppable` app:

https://github.com/horizontalsystems/unstoppable-wallet-ios/blob/master/UnstoppableWallet/UnstoppableWallet/Core/Providers/Erc20ContractInfoProvider.swift

This solution uses `Etherscan` for getting token info from transaction list.

**Comment by VitaliyYarkun** [comment]
Thanks for the answer, I will use the same approach and close this issue.
