### ISSUE TITLE
Send token issue

### ISSUE THREAD

**Issue by VitaliyYarkun** [horizontalsystems/ethereum-kit-ios#213]
Hi, I was trying to send some amount cash on erc20 token on MainNet, but I've faced a problem. `estimatedGasLimit` - I receive success and estimated amount, then `sendSingle` also give success, I have a transaction hash, the transaction is listed in sender history, but it doesn't actually send anything. Etherscan also couldn't find the transaction details by hash. Maybe you can point me out where could be the problem?

**Comment by esen** [comment]
Could you provide some more info. I'd suggest to create the Kit instance with `minLogLevel` set to `verbose` and inspect the logs.

**Comment by VitaliyYarkun** [comment]
@esen, thanks for your answer. I've figured out the problem. The case was in a very small fee rate which was basically hardcoded. So I updated fee rate logic using your BlockchainFeeRateKit and everything works fine. I will close this issue.
