### ISSUE TITLE
Incubed license

### ISSUE THREAD

**Issue by Cyclic** [horizontalsystems/ethereum-kit-ios#290]
It's confusing that EthereumKit is MIT licensed, but references Inc3 libraries, which is AGPL. Can you please explain how this is possible?

**Comment by esengulov** [comment]
> It's confusing that EthereumKit is MIT licensed, but references Inc3 libraries, which is AGPL. Can you please explain how this is possible?

hi @Cyclic 

We will have to digg deeper.  The inc3 libraries are currently commented out in the code and not being used in the production app in any way. Should you be concerned for any reason, you have an option not to use these libraries .

Here are som links:

- https://softwareengineering.stackexchange.com/questions/150534/want-to-use-a-lib-for-my-project-confused-with-license-agpl-vs-mit-license
- https://softwareengineering.stackexchange.com/questions/107883/agpl-what-you-can-do-and-what-you-cant

**Comment by Cyclic** [comment]
Thank you! I spoke to an expert about this, and they stated that even if the code is commented out, if it makes it into the final product, then it's going to carry the GPL license. Think of it like a book. If the book is readable online, it still carries the copyright. The best solution to this problem is to yank the code out of anything that ships to the client, rather than comment it out. Since the license is AGPL, even if the code is hosted, the license carries with it.

Thanks for getting back to me!
