### ISSUE TITLE
Sending NFT & Getting extra NFT info

### ISSUE THREAD

**Issue by 13adahan** [horizontalsystems/ethereum-kit-ios#344]
Hi, i am a big fan of your projects. I was wondering if there will be a function for sending NFT's and if there is a way to get extra info on an nft received like image / name

thank you

**Comment by ealymbaev** [comment]
It is already being implemented in:

https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/4459
https://github.com/horizontalsystems/unstoppable-wallet-ios/issues/4460

Btw, these features are already ready in `NftKit` and will be available in application in next version
