### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by yuzushioh** [horizontalsystems/ethereum-kit-ios#80]
Hi everyone!
I am Ryo and am an author of EthereumKit. I found this repo today. I looked though the codebase and it looks like this repo shares a same codebase with my framework. Now im wondering if you guys could buy my framework off from me in some way because I am not much working on it anymore but you guys look like you are. Let me know if you are interested. My email is on my profile.

Thank you

**Comment by esengulov** [comment]
> Hi everyone!
> I am Ryo and am an author of EthereumKit. I found this repo today. I looked though the codebase and it looks like this repo shares a same codebase with my framework. Now im wondering if you guys could buy my framework off from me in some way because I am not much working on it anymore but you guys look like you are. Let me know if you are interested. My email is on my profile.
> 
> Thank you

Thanks Ryo, 
We are not interested in buying but thanks for the offer :)
